name: Test api meme autotests

on: 
  workflow_dispatch:
    inputs: 
      deployment_target:
        description: select tests
        required: true
        type: choice
        default: smoke
        options:
          - smoke
          - regression
          - extended
          - all

permissions:
  contents: read
  pages: write
  id-token: write

jobs: 
  
  download-history:
    runs-on: ubuntu-latest
    name: Download history
    steps:
    - name: setup Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.13"
    - run: >
          ARTIFACT_ID=$(curl -L 
          -H "Accept: application/vnd.github+json" 
          -H "X-GitHub-Api-Version: 2022-11-28" 
          "https://api.github.com/repos/AlenaMakk91/test_api_meme_emakovskaya/actions/artifacts?name=allure-results" 
          | python -c "import sys, json; print(json.load(sys.stdin)['artifacts'][0]['id']);") 
          &&
          curl -L 
          -H "Accept: application/vnd.github+json" 
          -H "Authorization: Bearer ${{ secrets.TOKEN }}" 
          -H "X-GitHub-Api-Version: 2022-11-28" 
          https://api.github.com/repos/AlenaMakk91/test_api_meme_emakovskaya/actions/artifacts/$ARTIFACT_ID/zip 
          -o artifacts.zip &&
          REPORT_ID=$(curl -L 
          -H "Accept: application/vnd.github+json" 
          -H "X-GitHub-Api-Version: 2022-11-28" 
          "https://api.github.com/repos/AlenaMakk91/test_api_meme_emakovskaya/actions/artifacts?name=github-pages" 
          | python -c "import sys, json; print(json.load(sys.stdin)['artifacts'][0]['id']);") 
          &&
          curl -L 
          -H "Accept: application/vnd.github+json" 
          -H "Authorization: Bearer ${{ secrets.TOKEN }}" 
          -H "X-GitHub-Api-Version: 2022-11-28" 
          https://api.github.com/repos/AlenaMakk91/test_api_meme_emakovskaya/actions/artifacts/$REPORT_ID/zip 
          -o pages.zip
    - run: mkdir allure-results && unzip artifacts.zip -d allure-results
    - run: mkdir old_pages pages_history && unzip pages.zip -d old_pages && tar -xvf old_pages/artifact.tar -C pages_history
    - run: cp pages_history/history/* allure-results && cp -r pages_history/history allure-results
    - name: Store allure history
      uses: actions/upload-artifact@v6
      with:
        name: allure-results
        path:
          allure-results
        retention-days: 1
        

     
  Run-tests:
    runs-on: ubuntu-latest
    needs: download-history
    name: run autotests
    steps:
      - name: Установка необходимых библиотек
        run: |
          sudo apt-get update
          sudo apt-get install -y libkrb5-dev
      - name: Checkout autotests
        uses: actions/checkout@v6
      - name: set up Python environment
        uses: actions/setup-python@v6
        with:
           python-version: '3.13'
      - name: Install dependencies.
        run: pip install -r requirements.txt
      - name: Download all workflow run artifacts
        uses: actions/download-artifact@v4
      - name: run all tests
        if: "github.event.inputs.deployment_target == 'all'"
        run: pytest --alluredir=allure-results
        continue-on-error: true
      - name: run smoke tests
        if: "github.event.inputs.deployment_target == 'smoke'"
        run: pytest -m smoke --alluredir=allure-results
        continue-on-error: true
      - name: run regression tests
        if: "github.event.inputs.deployment_target == 'regression'"
        run: pytest -m regression --alluredir=allure-results
        continue-on-error: true
      - name: run extended tests
        if: "github.event.inputs.deployment_target == 'extended'"
        run: pytest -m extended --alluredir=allure-results
        continue-on-error: true
      - name: Store allure results
        uses: actions/upload-artifact@v6
        with:
          name: allure-results-${{ github.run_id }}
          path:
            allure-results
          retention-days: 1


  generate-report:
    name: Generate report
    runs-on: ubuntu-latest
    needs: Run-tests
    steps:
      - name: Install Java
        uses: actions/setup-java@v5
        with:
          distribution: 'microsoft'
          java-version: '21'
      - name: Install Allure
        run: sudo wget https://github.com/allure-framework/allure2/releases/download/2.24.1/allure-2.24.1.tgz && sudo tar -zxvf allure-2.24.1.tgz -C /opt/ && sudo ln -s /opt/allure-2.24.1/bin/allure /usr/bin/allure
      - name: Download all workflow run artifacts
        uses: actions/download-artifact@v4
      - run: allure generate -c allure-results -o _site
      - name: Store generated report
        uses: actions/upload-artifact@v6
        with:
          name: _site
          path:
            _site
          retention-days: 1
  

  publish-report:
    runs-on: ubuntu-latest
    needs: generate-report
    name: Report publication
    steps:
      - name: Download all workflow run artifacts
        uses: actions/download-artifact@v4
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v4
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
